root = "/app/backend"
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/scanner ./services/scanner"
bin = "bin/scanner"
include_ext = ["go"]
include_dir = ["services/scanner", "lib"]
exclude_dir = ["bin", ".git", "vendor"]
delay = 300

[log]
time = true

[run]
cmd = "bin/scanner"