root = "/app/backend"
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/thumbd ./services/thumbd"
bin = "bin/thumbd"
include_ext = ["go"]
include_dir = ["services/thumbd", "lib"]
exclude_dir = ["bin", ".git", "vendor"]
delay = 300

[log]
time = true

[run]
cmd = "bin/thumbd"