root = "/app/backend"
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/exifd ./services/exifd"
bin = "bin/exifd"
include_ext = ["go"]
include_dir = ["services/exifd", "lib"]
exclude_dir = ["bin", ".git", "vendor"]
delay = 300

[log]
time = true

[run]
cmd = "bin/exifd"
